# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/smartisan/sdm660-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter osborn oxford,$(TARGET_DEVICE)),)

endif
